[project]
name = "fastflowml"
version = "0.5.0"
description="a wrapper around the awesome FastFlowLM project from AMD(c) requires flastflowlm to be installed"
requires-python = ">=3.14"
readme = "README.md"
dependencies = [
    "beautifulsoup4",
    "ddgs",
    "markdownify",
    "openai",
    "playwright",
    "requests",
    "selenium",
]
authors = [
    { name = "Remko Weingarten", email = "remko66@gmail.com" }
]

[project.urls]
Homepage = "https://github.com/remko66/FastFlowLM"